version: 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - clean-code
      - test:
          requires:
            - clean-code
      - race:
          requires:
            - clean-code
      - compile_cmds:
          requires:
            - clean-code
      - check_licenses:
          requires:
            - clean-code
jobs:
  clean-code:
    <<: *golang-template
    steps:
      - checkout
      - run:
          name: Install dep
          command: |
            wget https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
            mv dep-linux-amd64 dep
            chmod +x dep
      - run:
          name: Install gometalinter
          command: |
            go get -u golang.org/x/lint/golint
            go get github.com/alecthomas/gometalinter
      - run:
          name: Install ineffassign
          command: go get github.com/gordonklaus/ineffassign
      - run:
          name: Check vendored dependencies
          command: |
            ./dep version
            ./dep status
            ./dep ensure -vendor-only
            git status
            if [[ -n "$(git status --porcelain vendor)" ]]; then
              echo 'vendor/ is out-of-date: run `dep ensure -vendor-only` and then check in the changes'
              echo 'If `dep ensure` results in no changes, make sure you are using the latest relase of dep'
              git status --porcelain vendor
              exit 1
            fi
      - run:
          name: vet
          command: |
            go vet -composites=false ./cmds/... ./pkg/... ./
      - run:
          name: gofmt
          command: |
            test -z "$(gofmt -s -l $(find -name '*.go' | grep -v /vendor/))"
      - run:
          name: gometalinter
          command: |
              gometalinter --vendor ./... --disable-all --enable=golint \
                --exclude="exported (function|type|const|method|var) (\w|_|\.)+ should have comment" \
                --exclude="don't use underscores" \
                --exclude="don't use ALL_CAPS" \
                --exclude="comment on exported (function|type|const|method|var) (\w|_|\.)+ should be of the form" \
                --exclude="package comment should be of the form" \
                --exclude="(function|type|const|method|var|type field|struct field) (\w|_|\.)+ should be (\w|_|\.)+" \
                --exclude="stutter" \
                --exclude="which can be annoying to use"
      - run:
          name: ineffassign
          command: ineffassign .
  compile_cmds:
    <<: *golang-template
    steps:
      - checkout
      - run:
          name: build all 
          command: |
            cd cmds
            go install -a ./...
