version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/u-root/cpu
    environment:
      - CGO_ENABLED: 0
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build ./...
      - run: go test -v ./...
      - run: GOARCH=arm go build ./...
      - run: GOARCH=arm64 go build ./...
      - run: GOARCH=mips go build ./...
      - run: GOARCH=mips64 go build ./...
      - run: GOARCH=mips64le go build ./...
      - run: GOARCH=mipsle go build ./...
      - run: GOARCH=ppc64 go build ./...
      - run: GOARCH=ppc64le go build ./...
      - run: GOARCH=s390x go build ./...
